edition = "2021"
format_strings = false
reorder_imports = true
reorder_modules = true
wrap_comments = true
comment_width = 80
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
fn_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
max_width = 100
merge_derives = true
imports_granularity = "Crate"
normalize_comments = true
combine_control_expr = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
trailing_comma = "Vertical"
use_small_heuristics = "Default"
use_try_shorthand = true
use_field_init_shorthand = true
unstable_features = true
version = "Two"